


3-Guarda el csv con las columnas limpias para seguir trabajando con este dataframe limpio.


1- Columna de species: si exploramos esta columna en detalle nos podemos dar cuenta que tenemos muchos valores únicos y esto hace que sea muy difícil trabajar con esta columna. Lo que vamos a hacer es clasificar los tiburones en 5 especies diferentes, las más comunes, que incluyen el tiburón blanco (White), el tiburón tigre (Tiger ), el tiburón gris (Grey), el tiburón limón (Lemon) y el tiburón toro (Bull). El resto de las especies las incluiremos en un único grupo que podremos llamar "Unspecified". Ahora nos podemos sentir un poco abrumadas y no saber como enfrentarnos a este reto, pero don't worry, os dejamos por aquí unas 💡 pistas 💡 para que os ayuden a entender cómo hacerlo.
   - Los valores de las columnas son strings por lo que podremos usar regex para buscar palabras clave en cada celda y asignarlo a una de las categorías que hemos definido previamente.
   - Tendremos que crearnos una función que aplicaremos sobre nuestra columna species_ para que nos devuelva una nueva columna con los valores clasificados en función de los patrones de regex que hayamos definido.


In [1]:
import pandas as pd
import numpy as np
import re
df= pd.read_csv('../Ficheros/attack_limpieza1.csv')

In [2]:
patron_blanco = r".*[Ww](hite|HITE).*"
patron_tiger = r".*[Tt](iger|IGER).*"
patron_grey = r".*[Gg](rey|REY).*"
patron_lemon = r".*[Ll](emon|EMON).*"
patron_bull = r".*[Bb](ull|ULL).*"
patron_nan = r"(NAN)"

In [3]:
df=df.fillna("NAN")

In [4]:
def cambiar_especie(x):
    if re.findall(patron_blanco,x):
        return x.replace(x,'White')
    elif re.findall(patron_tiger,x):
        return x.replace(x,'Tiger')
    elif re.findall(patron_grey,x):
        return x.replace(x,'Grey')
    elif re.findall(patron_lemon,x):
        return x.replace(x,'Lemon')
    elif re.findall(patron_bull,x):
        return x.replace(x,'Bull')
    elif re.findall(patron_nan,x):
        return x.replace(x,'NAN')
    else:
        return x.replace(x,"Unspecified")
    


In [5]:
df['species_']= df['species_'].apply(cambiar_especie)

In [6]:
df= df.apply(lambda x: x.replace('NAN', np.nan))

In [7]:
df['species_'].unique()

array([nan, 'Tiger', 'White', 'Unspecified', 'Bull', 'Grey', 'Lemon'],
      dtype=object)

In [8]:
df.to_csv("../Ficheros/attack_limpieza2.csv")

2.Columna de age: es una columna de tipo string pero debería ser de tipo integer. Además, en esta columna nos vamos a encontrar con algunos errores tipográficos, estos incluyen:

    Edad en formato string
    Edades separadas por &, or, to, >
    Edades con ?

Vamos con algunas :bombilla: pistas :bombilla: para que os ayuden a entender cómo hacerlo:

    Primero tendremos que eliminar todos esos símbolos especiales que nos aparecen. De nuevo, podremos usar regex para extraer unicamente los números que es lo que nos interesa. Usar este regex en una función para sacar solo los números.
    Puede que os salga un error similar a este:
    TypeError: expected string or bytes-like object
    Para solucionar este problema, antes de nada tendréis que ejecutar este código para que no os de error:
    df['nombre_columna'] = df['nombre_columna'].astype(str)
    Una vez que hayáis extraido los números, os daréis cuenta que hay celdas que tienen más de una edad. Tendréis que decidir que hacer en esos casos. Os dejamos por aquí una posible opción usando un método de Pandas que os puede resultar super útil. El método explode, aqui.
    Por último cambiad el tipo de la columna de string a integer.

In [9]:
df['age'].unique() 

array([nan, 'young', '14', '19', '20', '15', '21', '27', '36', '25', '6',
       '16', '50', '13 or 14', '57', '11', '48', '18', '52', '12', '32',
       '10', '34', '30', '60', '33', '29', '54', '41', '37', '56', '69',
       '38', '55', '35', '46', '45', '40s', '28', '24', '26', '49', '22',
       '7', '31', '17', '40', '13', '42', '3', '8', '82', '73', '20s',
       '68', '51', '39', '58', 'Teen', '47', '61', '65', '66', '43',
       '60s', '9', '72', '59', '64', '23', '71', '44', '62', '63', '70',
       '18 months', '53', '30s', '50s', 'teen', '77', '74', '28 & 26',
       '5', '86', '18 or 20', '12 or 13', '46 & 34', '28, 23 & 30',
       'Teens', '36 & 26', '8 or 10', '84', '\xa0 ', ' ', '30 or 36',
       '6½', '21 & ?', '75', '33 or 37', 'mid-30s', '23 & 20', ' 30',
       '7      &    31', ' 28', '20?', "60's", '32 & 30', '16 to 18',
       '87', '67', 'Elderly', 'mid-20s', 'Ca. 33', '74 ', '45 ',
       '21 or 26', '20 ', '>50', '18 to 22', 'adult', '9 & 12', '? & 19',
     

In [10]:
df=df.fillna("NAN")

In [11]:
patron_edades= r"[\d+]"

In [12]:
def cambiar_edades(x):
    if re.findall(patron_edades,x):
        return x
    else:
        return 'NAN'



In [13]:
df['nuevas_edades']= df['age'].apply(cambiar_edades)

In [14]:
df['nuevas_edades'].unique()

array(['NAN', '14', '19', '20', '15', '21', '27', '36', '25', '6', '16',
       '50', '13 or 14', '57', '11', '48', '18', '52', '12', '32', '10',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '69', '38',
       '55', '35', '46', '45', '40s', '28', '24', '26', '49', '22', '7',
       '31', '17', '40', '13', '42', '3', '8', '82', '73', '20s', '68',
       '51', '39', '58', '47', '61', '65', '66', '43', '60s', '9', '72',
       '59', '64', '23', '71', '44', '62', '63', '70', '18 months', '53',
       '30s', '50s', '77', '74', '28 & 26', '5', '86', '18 or 20',
       '12 or 13', '46 & 34', '28, 23 & 30', '36 & 26', '8 or 10', '84',
       '30 or 36', '6½', '21 & ?', '75', '33 or 37', 'mid-30s', '23 & 20',
       ' 30', '7      &    31', ' 28', '20?', "60's", '32 & 30',
       '16 to 18', '87', '67', 'mid-20s', 'Ca. 33', '74 ', '45 ',
       '21 or 26', '20 ', '>50', '18 to 22', '9 & 12', '? & 19',
       '9 months', '25 to 35', '23 & 26', '1', '33 & 37', '25 or 28',
       '

In [15]:
patron_s=r'[s]'

In [16]:
def cambiar_s(x):
    if re.findall(patron_s,x):
        return x.strip(patron_s)
    else:
        return x

In [17]:
df['nuevas_edades']=df['nuevas_edades'].apply(cambiar_s)

In [18]:
df['nuevas_edades'].unique() 

array(['NAN', '14', '19', '20', '15', '21', '27', '36', '25', '6', '16',
       '50', '13 or 14', '57', '11', '48', '18', '52', '12', '32', '10',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '69', '38',
       '55', '35', '46', '45', '40', '28', '24', '26', '49', '22', '7',
       '31', '17', '13', '42', '3', '8', '82', '73', '68', '51', '39',
       '58', '47', '61', '65', '66', '43', '9', '72', '59', '64', '23',
       '71', '44', '62', '63', '70', '18 month', '53', '77', '74',
       '28 & 26', '5', '86', '18 or 20', '12 or 13', '46 & 34',
       '28, 23 & 30', '36 & 26', '8 or 10', '84', '30 or 36', '6½',
       '21 & ?', '75', '33 or 37', 'mid-30', '23 & 20', ' 30',
       '7      &    31', ' 28', '20?', "60'", '32 & 30', '16 to 18', '87',
       '67', 'mid-20', 'Ca. 33', '74 ', '45 ', '21 or 26', '20 ', '>50',
       '18 to 22', '9 & 12', '? & 19', '9 month', '25 to 35', '23 & 26',
       '1', '33 & 37', '25 or 28', '37, 67, 35, 27,  ? & 27',
       '21, 34,24 & 3

In [19]:
patron_palabra=r'(month)|(Both)|(both)'

In [20]:
def cambiar_month(x):
    if re.findall(patron_palabra,x):
        return re.sub(patron_palabra, "", x)
    else:
        return x

In [21]:
df['nuevas_edades']=df['nuevas_edades'].apply(cambiar_month)

In [22]:
df['nuevas_edades'].unique() 

array(['NAN', '14', '19', '20', '15', '21', '27', '36', '25', '6', '16',
       '50', '13 or 14', '57', '11', '48', '18', '52', '12', '32', '10',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '69', '38',
       '55', '35', '46', '45', '40', '28', '24', '26', '49', '22', '7',
       '31', '17', '13', '42', '3', '8', '82', '73', '68', '51', '39',
       '58', '47', '61', '65', '66', '43', '9', '72', '59', '64', '23',
       '71', '44', '62', '63', '70', '18 ', '53', '77', '74', '28 & 26',
       '5', '86', '18 or 20', '12 or 13', '46 & 34', '28, 23 & 30',
       '36 & 26', '8 or 10', '84', '30 or 36', '6½', '21 & ?', '75',
       '33 or 37', 'mid-30', '23 & 20', ' 30', '7      &    31', ' 28',
       '20?', "60'", '32 & 30', '16 to 18', '87', '67', 'mid-20',
       'Ca. 33', '74 ', '45 ', '21 or 26', '20 ', '>50', '18 to 22',
       '9 & 12', '? & 19', '9 ', '25 to 35', '23 & 26', '1', '33 & 37',
       '25 or 28', '37, 67, 35, 27,  ? & 27', '21, 34,24 & 35', '30 & 32',
  

In [23]:
patron_or=r'[\D+]'

In [24]:
def cambiar_or(x):
    if re.findall(patron_or,x):
        return re.split(patron_or, x)[0]
    else:
        return x
   

In [25]:
df['nuevas_edades']=df['nuevas_edades'].apply(cambiar_or)

In [26]:
df['nuevas_edades'].unique()

array(['', '14', '19', '20', '15', '21', '27', '36', '25', '6', '16',
       '50', '13', '57', '11', '48', '18', '52', '12', '32', '10', '34',
       '30', '60', '33', '29', '54', '41', '37', '56', '69', '38', '55',
       '35', '46', '45', '40', '28', '24', '26', '49', '22', '7', '31',
       '17', '42', '3', '8', '82', '73', '68', '51', '39', '58', '47',
       '61', '65', '66', '43', '9', '72', '59', '64', '23', '71', '44',
       '62', '63', '70', '53', '77', '74', '5', '86', '84', '75', '87',
       '67', '1', '2', '81', '78'], dtype=object)

In [27]:
type(df.loc[162]["nuevas_edades"])

str

In [28]:
def buscar(x):
    if x == "":
        return np.nan
    else:
        return x

In [29]:
df['nuevas_edades']=df['nuevas_edades'].apply(buscar)

In [30]:
df['nuevas_edades'].unique()

array([nan, '14', '19', '20', '15', '21', '27', '36', '25', '6', '16',
       '50', '13', '57', '11', '48', '18', '52', '12', '32', '10', '34',
       '30', '60', '33', '29', '54', '41', '37', '56', '69', '38', '55',
       '35', '46', '45', '40', '28', '24', '26', '49', '22', '7', '31',
       '17', '42', '3', '8', '82', '73', '68', '51', '39', '58', '47',
       '61', '65', '66', '43', '9', '72', '59', '64', '23', '71', '44',
       '62', '63', '70', '53', '77', '74', '5', '86', '84', '75', '87',
       '67', '1', '2', '81', '78'], dtype=object)

In [31]:
df.sample(20)

Unnamed: 0   case_number  year             country  \
424          424    2016.06.27  2016                 usa   
5635        5635  1906.02.14.R  1906         new zealand   
3039        3039  1984.09.30.b  1984                 usa   
5593        5593    1908.05.10  1908                 usa   
1358        1358    2008.11.06  2008         philippines   
2530        2530  1995.07.28.b  1995                 usa   
2481        2481    1996.02.05  1996  dominican republic   
5209        5209    1930.01.22  1930              mexico   
3670        3670    1967.09.01  1967    papua new guinea   
1107        1107    2011.03.10  2011           australia   
1121        1121  2011.01.12.R  2011              mexico   
5395        5395  1921.11.27.a  1921           australia   
1040        1040  2011.08.28.b  2011           australia   
5892        5892    1887.10.00  1887             bahamas   
5436        5436    1918.03.22  1918           australia   
5262        5262    1928.05.17  1928               india   
3079        3079    1983.11.10  1983        south africa   
5508        5508    1913.09.03  1913             croatia   
3186        3186    1981.06.12  1981                 usa   
5663        5663    1904.02.07  1904           australia   

                                               activity  age     species_  \
424                                                 NAN   35  Unspecified   
5635                                           Swimming  NAN  Unspecified   
3039                     Surfing (sitting on his board)   25        White   
5593                                                NAN  NAN  Unspecified   
1358                                            Fishing   39          NAN   
2530                                           Standing   18          NAN   
2481  Boeing 757 enroute from Porta Plata plunged in...  NAN          NAN   
5209               Fishing schooner Jose Luis foundered  NAN          NAN   
3670                                       Spearfishing   23  Unspecified   
1107                                            Surfing  NAN          NAN   
1121                            Attempting to fix motor   37          NAN   
5395                 Wading to dinghy, carrying his son   40          NAN   
1040                                           Swimming   48  Unspecified   
5892            Sea disaster, wreck of the Alfred Watts  NAN          NAN   
5436                                            Surfing  NAN  Unspecified   
5262                                                NAN  NAN  Unspecified   
3079                                           Swimming  NAN  Unspecified   
5508                                                NAN  NAN  Unspecified   
3186                                                NAN  NAN  Unspecified   
5663                             Swimming after his hat  NAN          NAN   

                      date  mes fatal_ sex2 nuevas_edades  
424            27-Jun-2016  Jun      n    M            35  
5635  Reported 14-Feb-1906  Feb    NAN    M           NaN  
3039           30-Sep-1984  Sep      n    M            25  
5593           10-May-1908  May    NAN    M           NaN  
1358           06-Nov-2008  Nov      y    M            39  
2530           28-Jul-1995  Jul      n    M            18  
2481           05-Feb-1996  Feb      y  NAN           NaN  
5209           22-Jan-1930  Jan      y  NAN           NaN  
3670           01-Sep-1967  Sep      y    M            23  
1107           10-Mar-2011  Mar      n    M           NaN  
1121  Reported 12-Jan 2011  NAN      n    M            37  
5395           27-Nov-1921  Nov      n    M            40  
1040           28-Aug-2011  Aug    NAN    M            48  
5892          October 1887  NAN      y    M           NaN  
5436           22-Mar-1918  Mar      n    M           NaN  
5262           27-May-1928  May    NAN    M           NaN  
3079           10-Nov-1983  Nov    NAN    F           NaN  
5508           03-Sep-1913  Sep      n    M    

In [32]:
def cambiar_int(x):
    if type(x) == str:
        return int(x)
    else:
        return x

In [33]:
df['nuevas_edades']=df['nuevas_edades'].apply(cambiar_int)

In [34]:
df['nuevas_edades'].unique()

array([nan, 14., 19., 20., 15., 21., 27., 36., 25.,  6., 16., 50., 13.,
       57., 11., 48., 18., 52., 12., 32., 10., 34., 30., 60., 33., 29.,
       54., 41., 37., 56., 69., 38., 55., 35., 46., 45., 40., 28., 24.,
       26., 49., 22.,  7., 31., 17., 42.,  3.,  8., 82., 73., 68., 51.,
       39., 58., 47., 61., 65., 66., 43.,  9., 72., 59., 64., 23., 71.,
       44., 62., 63., 70., 53., 77., 74.,  5., 86., 84., 75., 87., 67.,
        1.,  2., 81., 78.])

3 Guarda el csv con las columnas limpias para seguir trabajando con este dataframe limpio

In [35]:
df.to_csv("../Ficheros/attack_limpieza2.csv")