In [46]:
import pandas as pd
import numpy as np
import sidetable
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df= pd.read_csv('../Ficheros/attack_limpieza3.csv', index_col = 0)

In [47]:
df

case_number  year     country                         activity  age  \
0       1800.00.00  1977  seychelles  a corsair's boat was overturned  NaN   
1     1797.05.28.R  1977         NaN                Dropped overboard  NaN   
2       1792.09.12  1977     england                          Fishing  NaN   
3       1791.00.00  1977   australia                              NaN  NaN   
4       1788.05.10  1977   australia                          Fishing  NaN   
...            ...   ...         ...                              ...  ...   
6279  1804.02.26.R  1977   australia                              NaN  NaN   
6280    1803.05.17  1977         usa                              NaN  NaN   
6281    1803.03.00  1977   australia                              NaN  NaN   
6282  1802.04.13.R  1977       india                              NaN  NaN   
6283  1801.12.18.R  1977         NaN  Standing on landed shark's tail  NaN   

         species_                  date  mes fatal_ sex2  nuevas_edades  
0             NaN                  1800  NaN      y    F            NaN  
1             NaN  Reported May-28-1797  May      y  NaN            NaN  
2             NaN           12-Sep-1792  Sep      y    M            NaN  
3             NaN                  1791  NaN      y    F            NaN  
4             NaN           10-May-1788  May      n  NaN            NaN  
...           ...                   ...  ...    ...  ...            ...  
6279          NaN  Reported 26-Feb-1804  Feb      n  NaN            NaN  
6280          NaN           May-17-1803  May      n    M            NaN  
6281          NaN              Mar-1803  Mar      n    M            NaN  
6282          NaN  Reported Apr-13-1802  Apr      y  NaN            NaN  
6283  Unspecified  Reported 18-Dec-1801  Dec      y    F            NaN  

[6284 rows x 11 columns]

In [48]:
df.stb.missing()

missing  total    percent
nuevas_edades     2860   6284  45.512412
species_          2831   6284  45.050923
age               2820   6284  44.875875
fatal_             607   6284   9.659453
mes                570   6284   9.070656
sex2               564   6284   8.975175
activity           542   6284   8.625080
country             50   6284   0.795672
case_number          1   6284   0.015913
year                 0   6284   0.000000
date                 0   6284   0.000000

Es el momento de ponernos a trabajar con los valores nulos de nuevo 💪🏽. A lo largo de este ejercicio de pair programming vamos a intentar eliminar los valores nulos de nuestras columnas. En la lección hemos aprendido varios métodos de skelarn intentemos aplicarlos todos. Manos a la obra!

1- Es el momento de eliminar los nulos:

Reemplazad los valores nulos de la columna age por la media de la edad usando el método SimpleImputer.

In [49]:
#creamos la instancia

imputer_age = SimpleImputer(strategy='mean', missing_values=np.nan)

In [50]:
imputer_age = imputer_age.fit(df[['nuevas_edades']])

In [51]:
df['nuevas_edades'] = imputer_age.transform(df[['nuevas_edades']])

In [52]:
df['nuevas_edades'].unique()

array([27.30169393, 14.        , 19.        , 20.        , 15.        ,
       21.        , 27.        , 36.        , 25.        ,  6.        ,
       16.        , 50.        , 13.        , 57.        , 11.        ,
       48.        , 18.        , 52.        , 12.        , 32.        ,
       10.        , 34.        , 30.        , 60.        , 33.        ,
       29.        , 54.        , 41.        , 37.        , 56.        ,
       69.        , 38.        , 55.        , 35.        , 46.        ,
       45.        , 40.        , 28.        , 24.        , 26.        ,
       49.        , 22.        ,  7.        , 31.        , 17.        ,
       42.        ,  3.        ,  8.        , 51.        , 39.        ,
       58.        , 47.        , 61.        , 43.        ,  9.        ,
       59.        , 23.        , 44.        , 62.        , 53.        ,
        5.        ,  1.        ,  2.        ])

In [53]:
df.stb.missing()

missing  total    percent
species_          2831   6284  45.050923
age               2820   6284  44.875875
fatal_             607   6284   9.659453
mes                570   6284   9.070656
sex2               564   6284   8.975175
activity           542   6284   8.625080
country             50   6284   0.795672
case_number          1   6284   0.015913
year                 0   6284   0.000000
date                 0   6284   0.000000
nuevas_edades        0   6284   0.000000

Reemplazad los valores nulos de la columna sex por la moda, usando el método SimpleImputer.

In [54]:
imputer_sex = SimpleImputer(strategy='most_frequent', missing_values=np.nan)

In [55]:
imputer_sex = imputer_sex.fit(df[['sex2']])

In [56]:
df['sex2'] = imputer_sex.transform(df[['sex2']])

In [57]:
df['sex2'].unique()

array(['F', 'M'], dtype=object)

In [58]:
df.stb.missing()

missing  total    percent
species_          2831   6284  45.050923
age               2820   6284  44.875875
fatal_             607   6284   9.659453
mes                570   6284   9.070656
activity           542   6284   8.625080
country             50   6284   0.795672
case_number          1   6284   0.015913
year                 0   6284   0.000000
date                 0   6284   0.000000
sex2                 0   6284   0.000000
nuevas_edades        0   6284   0.000000

Reemplazad los valores nulos de la columna type por el valor más frecuente (la moda) con el método SimpleImputer.

In [59]:
# No tenemos columan type, vamos a usar activity

In [60]:
imputer_act = SimpleImputer(strategy='most_frequent', missing_values=np.nan)

In [61]:
imputer_act = imputer_act.fit(df[['activity']])

In [62]:
df['activity'] = imputer_act.transform(df[['activity']])

In [63]:
df['activity'].unique()

array(["a corsair's boat was overturned", 'Dropped overboard', 'Fishing',
       ..., 'HBM Magpie foundered in a squall', 'Conch diver',
       "Standing on landed shark's tail"], dtype=object)

In [64]:
df.stb.missing()

missing  total    percent
species_          2831   6284  45.050923
age               2820   6284  44.875875
fatal_             607   6284   9.659453
mes                570   6284   9.070656
country             50   6284   0.795672
case_number          1   6284   0.015913
year                 0   6284   0.000000
activity             0   6284   0.000000
date                 0   6284   0.000000
sex2                 0   6284   0.000000
nuevas_edades        0   6284   0.000000

In [65]:
df.to_csv("../Ficheros/attack_limpieza5.csv")

Utilizad el método KNN Imputer para reemplazar todos los valores nulos de las columnas numéricas.

In [20]:
#volvemos a cargar el dataset para que resetee y vuelva a haber nulos

In [21]:
df= pd.read_csv('../Ficheros/attack_limpieza3.csv', index_col = 0)

In [22]:
numericas = df.select_dtypes(include = np.number)
numericas.sample(10)

year  nuevas_edades
6127  1977            NaN
1622  2006            7.0
5379  1922            NaN
1510  2007           16.0
3979  1962           31.0
1572  2007           20.0
3368  1975           21.0
2235  2000            NaN
2988  1986            NaN
2103  2001           52.0

In [23]:
# inciamos el KNNImputer y lo aplicamos a nuestras variables numéricas

imputerKNN = KNNImputer(n_neighbors=5)
imputerKNN.fit(numericas)

KNNImputer()

In [24]:
numericas_knn= imputerKNN.transform(numericas)

In [25]:
numericas_knn

array([[1977. ,   40.8],
       [1977. ,   40.8],
       [1977. ,   40.8],
       ...,
       [1977. ,   40.8],
       [1977. ,   40.8],
       [1977. ,   40.8]])

In [26]:
df_knn_imputer = pd.DataFrame(numericas_knn, columns = numericas.columns)

In [27]:
df_knn_imputer.head()

year  nuevas_edades
0  1977.0           40.8
1  1977.0           40.8
2  1977.0           40.8
3  1977.0           40.8
4  1977.0           40.8

In [28]:
columnas_knn = df_knn_imputer.columns
columnas_knn

Index(['year', 'nuevas_edades'], dtype='object')

In [29]:
df.drop(columnas_knn, axis = 1, inplace = True)

In [30]:
df[columnas_knn] = numericas_knn

In [31]:
df.isnull().sum()

case_number         1
country            50
activity          542
age              2820
species_         2831
date                0
mes               570
fatal_            607
sex2              564
year                0
nuevas_edades       0
dtype: int64

Utilizad el método Iterative Imputer para reemplazar todos los valores nulos de las columnas numéricas.

In [32]:
#volvemos a cargar el dataset para que resetee y vuelva a haber nulos

In [33]:
df= pd.read_csv('../Ficheros/attack_limpieza3.csv', index_col = 0)

In [34]:
numericas = df.select_dtypes(include = np.number)

In [35]:
numericas.isnull().sum()

year                0
nuevas_edades    2860
dtype: int64

In [36]:
# creamos una instancia del método Iterative Imputer con las características que queremos 
imputer = IterativeImputer(n_nearest_features=None, imputation_order='ascending', initial_strategy='median')

In [37]:
imputer.fit(numericas)


IterativeImputer(initial_strategy='median')

In [38]:
imputer.transform(numericas)

array([[1977.        ,   26.54317649],
       [1977.        ,   26.54317649],
       [1977.        ,   26.54317649],
       ...,
       [1977.        ,   26.54317649],
       [1977.        ,   26.54317649],
       [1977.        ,   26.54317649]])

In [39]:
numericas_imp = pd.DataFrame(imputer.transform(numericas), columns = numericas.columns)

In [40]:
numericas_imp.head()

year  nuevas_edades
0  1977.0      26.543176
1  1977.0      26.543176
2  1977.0      26.543176
3  1977.0      26.543176
4  1977.0      26.543176

In [41]:
df.drop(numericas_imp.columns, axis = 1, inplace = True)

In [42]:
df[numericas_imp.columns] = numericas_imp[numericas_imp.columns]

In [43]:
df.isnull().sum()

case_number         1
country            50
activity          542
age              2820
species_         2831
date                0
mes               570
fatal_            607
sex2              564
year                0
nuevas_edades       0
dtype: int64

¿Podríais explicar qué diferencia hay entre estos dos últimos métodos?

In [44]:
# En el método iterativeimputer creo que trabaja con todos los datos numericos del dataset para hacer la estimación
# En el método KNN imputer trabaja con los datos cercanos (neighbours) para hacer la estimación

2- Guardad el csv para seguir trabajando con el en los siguientes ejercicios de pair

In [66]:
# Quedó guardado tras aplicar el método simple imputer porque es el más completo